### PR TITLE
fix minor pin access bug

### PR DESCRIPTION
**Pull request by wfz0755**

### CODE REVIEW

**Comment by Rholais** [comment]
Thanks for the fix!
Is there any resulting improvement from this fix?

**Comment by wfz0755** [comment]
I just finished running all the cases. The result is shown below:
| case  |  WL            |  #sv      |  og WL       |  og #v   |  ot WL     |  ot #v  |  ww WL      |  #short  |  short a  |  #min a  |  #prl   |  #eol  |  #cut  |  #adj  |  #cnr   |  #spc  |  #o  |  tot        | now/ori     |
|-------|----------------|-----------|--------------|----------|------------|---------|-------------|----------|-----------|----------|---------|--------|--------|--------|---------|--------|------|-------------|-------------|
| 8t1   | 433584.3       | 32394     | 2172.12      | 445      | 419.07     | 0       | 5853.5      |  N/A     | 0.09      | 0        |  N/A    |  N/A   |  N/A   |  N/A   |  N/A    | 2      | 0    | 291305.31   | 1.000049126 |
| 8t2   | 7832656.58     | 325674    | 41036.47     | 6542     | 5291.9     | 0       | 54119.75    |  N/A     | 0.12      | 0        |  N/A    |  N/A   |  N/A   |  N/A   |  N/A    | 57     | 0    | 4700581.71  | 0.99992506  |
| 8t3   | 8718263.18     | 318303    | 65586.15     | 6602     | 5990.55    | 0       | 60553.45    |  N/A     | 231.71    | 0        |  N/A    |  N/A   |  N/A   |  N/A   |  N/A    | 96     | 0    | 5295331.34  | 0.999355761 |
| 8t4   | 26419880.43    | 729197    | 388623.23    | 29618    | 17721.49   | 0       | 205951.09   |  N/A     | 210.45    | 90       |  N/A    |  N/A   |  N/A   |  N/A   |  N/A    | 619    | 0    | 15761113.98 | 1.000298925 |
| 8t5   | 27802051.3     | 965546    | 150636.75    | 21840    | 5833.89    | 3       | 77203.15    |  N/A     | 62.65     | 148      |  N/A    |  N/A   |  N/A   |  N/A   |  N/A    | 361    | 0    | 16370540    | 1.000231995 |
| 8t6   | 35703514.33    | 1480728   | 242099.8     | 36492    | 16544.66   | 16      | 119149.51   |  N/A     | 14.95     | 271      |  N/A    |  N/A   |  N/A   |  N/A   |  N/A    | 549    | 0    | 21636717.79 | 1.000280703 |
| 8t7   | 65173353.22    | 2402487   | 402055.3     | 55583    | 32575.39   | 0       | 186348.71   |  N/A     | 171.39    | 343      |  N/A    |  N/A   |  N/A   |  N/A   |  N/A    | 199    | 0    | 38408621.22 | 0.999907066 |
| 8t8   | 65468212.16    | 2412163   | 402983.96    | 54459    | 32411.98   | 0       | 182755.68   |  N/A     | 180.58    | 392      |  N/A    |  N/A   |  N/A   |  N/A   |  N/A    | 189    | 0    | 38595625.12 | 0.999822916 |
| 8t9   | 54759612.27    | 2410625   | 358136.84    | 55296    | 26348.8    | 0       | 177596.47   |  N/A     | 12.7      | 491      |  N/A    |  N/A   |  N/A   |  N/A   |  N/A    | 115    | 0    | 33114609.84 | 0.999559176 |
| 8t10  | 68098159.3     | 2595706   | 1091463.6    | 99121    | 40703.74   | 0       | 237319.12   |  N/A     | 2769.29   | 619      |  N/A    |  N/A   |  N/A   |  N/A   |  N/A    | 958    | 0    | 42861890.98 | 1.003691412 |
| 9t1   | 641953.96      | 36866     | 12208.69     | 1536     | 756.51     | 742     | 11172.65    | 59       | 19.25     | 26       | 9       | 18     | 21     | 4      | 54      |  N/A   | 0    | 599603.58   | 1.003683577 |
| 9t2   | 24960763.71    | 811116    | 410068.88    | 34250    | 21913.56   | 23594   | 209801.9    | 1626     | 552.19    | 655      | 921     | 952    | 149    | 89     | 5879    |  N/A   | 0    | 21825109.92 | 0.996096413 |
| 9t3   | 842207.46      | 65550     | 12575.31     | 1658     | 1928.41    | 662     | 16180.28    | 54       | 15.96     | 68       | 152     | 68     | 29     | 11     | 107     |  N/A   | 0    | 967821.02   | 0.913009413 |
| 9t4   | 30491758.84    | 1031466   | 559455.22    | 45815    | 13258.78   | 3       | 120977.89   | 2551     | 1851.99   | 45       | 254     | 45     | 0      | 0      | 0       |  N/A   | 0    | 22478118.67 | 1.007418216 |
| 9t5   | 4780098.79     | 153560    | 13745.52     | 2700     | 1931.99    | 15      | 15051.14    | 1227     | 1275.67   | 2        | 142     | 13     | 0      | 0      | 0       |  N/A   | 0    | 4366603.43  | 1.324281414 |
| 9t6   | 66064387.59    | 1997978   | 746502.79    | 67075    | 25621.51   | 12486   | 456218.7    | 4157     | 1661.96   | 738      | 1206    | 916    | 370    | 49     | 1147    |  N/A   | 0    | 47441676.53 | 1.002214353 |
| 9t7   | 122554850.4    | 4833963   | 900952.4     | 102158   | 44904.17   | 24313   | 607227.92   | 2518     | 843.16    | 2050     | 21841   | 1676   | 765    | 68     | 3448    |  N/A   | 0    | 98874960.58 | 1.001400904 |
| 9t8   | 188474513.8    | 7365579   | 1212171.43   | 163443   | 72513.18   | 36389   | 729183.51   | 3042     | 1025.03   | 2897     | 4296    | 2827   | 1257   | 81     | 5876    |  N/A   | 0    | 136527531.4 | 0.999980784 |
| 9t9   | 285389181.7    | 12248470  | 1881878.35   | 276312   | 125267.88  | 60627   | 1213608.88  | 6753     | 1965.92   | 5189     | 6772    | 5171   | 3490   | 119    | 9456    |  N/A   | 0    | 214641493.3 | 1.000567329 |
| 9t10  | 282174555.2    | 12542976  | 1836487.71   | 255246   | 127061.53  | 60611   | 1412300.23  | 6943     | 1964.63   | 5083     | 6828    | 4797   | 2994   | 137    | 10344   |  N/A   | 0    | 214432669.9 | 1.00044288  |

Strangely, it seems that on average, the original one can achieve a better score...

**Comment by Rholais** [comment]
> 1.324281414

The degradation on `9t5` is significant.
Can you help rerun `9t5` without your fix to confirm whether the degradation comes from this change or not?

**Comment by wfz0755** [comment]
Sure, I reran 9t5 with the latest commit (./run.py 9t5 -s route eval -t 8)
And the score was  4374626.52, which is different from the table shown in the README.

**Comment by Rholais** [comment]
> 4374626.52

Then this fix actually improves `9t5`.
We may need to check which commit degraded this design.

**Comment by wfz0755** [comment]
Sure. I will check that when I get time.

**Comment by InfamousMeGa** [comment]
The routing solutions of 9t5 are the same, seems like Innovus 18.1 and 17.1 reported different scores for 9t5.

**Comment by Rholais** [comment]
> The routing solutions of 9t5 are the same, seems like Innovus 18.1 and 17.1 reported different scores for 9t5.

Thanks for the investigation!
Then it should be safe to merge the change.

**Pull request merged**
